apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "edgecep.labels" . | nindent 4 }}
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence false
    log_type all