apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  namespace: {{ .values.namespace}}
  labels:
    {{- include "edgecep.labels" . | nindent 4 }}
spec:
  selector:
    app: mqtt-broker
  ports:
    - name: mqtt
      port: {{ .Values.mqtt.servicePort }}
      targetPort: {{ .Values.mqtt.servicePort }}