apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "edgecep.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path      # provisioned by local-path-provisioner
  resources:
    requests:
      storage: {{ .Values.llmService.chromaStorage }}