mqtt:
  image: eclipse-mosquitto:2
  servicePort: 1883

dashboard:
  image: commonpoc.azurecr.io/dashboard-ui-arm64:2.0.1
  replicaCount: 1
  service:
    type: NodePort
    port: 8000
    nodePort: 30080

simulator:
  image: commonpoc.azurecr.io/simulator-arm64:3.0.0
  replicaCount: 1

cep:
  image: commonpoc.azurecr.io/cep-engine-arm64:1.0.3
  replicaCount: 1

mqttHost: mqtt-broker
mqttPort: 1883

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi

imagePullSecret:
  name: regcred
  dockerconfigjson: "eyJhdXRocyI6eyJjb21tb25wb2MuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6ImNvbW1vbnBvYyIsInBhc3N3b3JkIjoiSkk4MDgzKz1Ob2VybGZlL0N1dThieW8yT3RCTHdSNXoiLCJhdXRoIjoiWTI5dGJXOXVjRzlqT2twSk9EQTRNeXM5VG05bGNteG1aUzlEZFhVNFlubHZNazkwUWt4M1VqVjYifX19"

namespace: cep-edge

ollama:
  image: ollama/ollama:latest
  storage: 10Gi
  gpu:
    enabled: true
    count: 1
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 3Gi
  

llmService:
  image: commonpoc.azurecr.io/llm_service:2.0.3
  replicaCount: 1
  ollamaHost: "http://ollama:11434"
  ollamaModel: "gemma2:2b"
  chromaPath: "/app/incident_store"
  chromaStorage: 3Gi
  siteId: "SUBSTATION-ABU-01"

